FROM php:7.4-apache

USER root

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y libpng-dev zlib1g-dev libxml2-dev libzip-dev \
    libmcrypt-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libonig-dev \
    graphviz \
    curl \
    wget \
    nano joe \
    telnet \
    iputils-ping

RUN docker-php-ext-install mbstring zip gd pdo_mysql mysqli exif pcntl dom 

# Necessário para instalar o wkhtmltopdf(qt patched) no debian 10
RUN apt-get install -y xfonts-75dpi xfonts-base

COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf
RUN a2enmod rewrite

COPY . .

RUN chown -R www-data:www-data /var/www/html
COPY entrypoint.sh .

RUN ["chmod", "+x", "/var/www/html/entrypoint.sh"]

EXPOSE 80

CMD ./entrypoint.sh

